If:
  PathExclude: .*\.[c]
CompileFlags:
  # clang default to C++ 14 at the time of writing ... make it default to C++17 instead
  Add: [-std=c++17, -Wall, -Wextra, -Wshadow, -Wconversion, -Wpedantic]

---

If:
  PathMatch: .*\.[ch]
  CompileFlags:
    Add: [-std=c99, -Wall, -Wextra, -Wshadow, -Wconversion, -Wpedantic]
